Repository elementsinteractive/lgtm-ai, pull requests merged in 2025-06, with the labels that each got.

#44 fix(#41): handle empty PR titles and descriptions for GitHub
  src/lgtm_ai/git_client/github.py
Labels: fix

#45 feat: Add additional context for the LLM
  README.md
  poetry.lock
  pyproject.toml
  src/lgtm_ai/ai/prompts.py
  src/lgtm_ai/ai/schemas.py
  src/lgtm_ai/config/handler.py
  src/lgtm_ai/git_client/base.py
  src/lgtm_ai/git_client/github.py
  src/lgtm_ai/git_client/gitlab.py
  src/lgtm_ai/review/additional_context.py
  src/lgtm_ai/review/prompt_generators.py
  src/lgtm_ai/review/reviewer.py
  tests/config/conftest.py
  tests/config/test_handler.py
  tests/git_client/test_gitlab.py
  tests/review/test_additional_context.py
  tests/review/test_reviewer.py
  tests/review/utils.py
Labels: feature

#46 chore: add diagrams for lgtm
  assets/lgtm-diagram.excalidraw
  assets/lgtm-diagram.png
Labels: ignore-for-release

#49 fix: change correctness emoji
  README.md
  src/lgtm_ai/formatters/constants.py
  tests/formatters/test_markdown.py
Labels: fix

#53 feat(#52): add support for new gemini-pro-06-05
  ai_assessments/2025-06-12-newgem/review-pr-PR-1-trivial-1.md
  lgtm.toml
  src/lgtm_ai/ai/schemas.py
Labels: feature

#55 feat(#54): add support for gemini model wildcards
  README.md
  src/lgtm_ai/ai/agent.py
  src/lgtm_ai/ai/exceptions.py
  src/lgtm_ai/ai/schemas.py
  src/lgtm_ai/ai/utils.py
  tests/ai/test_utils.py
Labels: feature
